[project]
name = "cobrain"
version = "0.1.5"
description = "Cobrain CLI helps AI agents gather, organize and visualize owner's knowledge locally on device. Use it to back up and organize your knowledge, help AI agents read your mind, or map and track your learning progress."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "build>=1.5.0",
    "pyyaml>=6.0",
    "twine>=6.2.0",
    "xdk>=0.9.0",
]

[project.scripts]
cobrain = "cobrain.cli:main"
brn = "cobrain.cli:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.ruff]
target-version = "py311"

[tool.pyright]
pythonVersion = "3.11"

[tool.setuptools.package-data]
cobrain = ["html/*"]

[tool.deptry.per_rule_ignores]
DEP003 = ["cobrain"]
