import json
import sys
from datetime import date
from pathlib import Path

from hippo.directories import get_hippo_dir, get_graph_path
from hippo.graph.category import infer_categories, save_categories
from hippo.topics.topic import Topic
from hippo.yaml_utils import read_yaml


def _compute_activity(updated_at: str) -> float:
    if not updated_at:
        return 0.0
    try:
        updated = date.fromisoformat(updated_at)
        today = date.today()
        days_diff = (today - updated).days
        return max(0.0, 1.0 - days_diff / 90.0)
    except ValueError:
        return 0.0


def _compute_activity_label(activity: float) -> str | None:
    if activity >= 0.85:
        return "H"
    elif activity >= 0.15:
        return "W"
    return None


def _load_topics() -> list[Topic]:
    graph_path = get_graph_path()
    if not graph_path.exists():
        print("Error: Run hippo sync first", file=sys.stderr)
        sys.exit(1)

    data = read_yaml(graph_path)
    if not data:
        print("Error: No topics found", file=sys.stderr)
        sys.exit(1)

    return [Topic.from_dict(t) for t in data.get("topics", [])]


def _infer_test_categories(topics: list[Topic]) -> dict[str, dict]:
    topic_dicts = [t.to_dict() for t in topics]
    categories = infer_categories(topic_dicts)
    save_categories(categories)
    return {c.id: {"id": c.id, "title": c.title, "color": c.color} for c in categories}


def build_html() -> Path:
    hippo_dir = get_hippo_dir()
    vault_name = hippo_dir.parent.name

    topics = _load_topics()
    # categories = load_categories()  # PERM: generated by sync
    categories = _infer_test_categories(
        topics
    )  # TEMP: generate from graph during testing

    topic_map: dict[str, dict] = {}
    for topic in topics:
        activity = _compute_activity(topic.updated_at)
        topic_map[topic.id] = {
            "id": topic.id,
            "title": topic.title,
            "aliases": topic.aliases,
            "progress": topic.progress,
            "created_at": topic.created_at,
            "updated_at": topic.updated_at,
            "category": topic.category,
            "parent": topic.parent,
            "related": topic.related,
            "sources": topic.sources,
            "word_count": topic.word_count,
            "activity": activity,
            "activityLabel": _compute_activity_label(activity),
        }

    parent_links: list[dict] = []
    related_links: list[dict] = []
    for topic in topics:
        if topic.parent and topic.parent in topic_map:
            parent_links.append({"source": topic.parent, "target": topic.id})

        for related_id in topic.related:
            if related_id in topic_map:
                related_links.append({"source": topic.id, "target": related_id})

    topic_count = len(topics)
    connection_count = len(parent_links) + len(related_links)

    output = {
        "nodes": list(topic_map.values()),
        "parentLinks": parent_links,
        "relatedLinks": related_links,
        "categories": list(categories.values()),
        "vaultName": vault_name,
        "topicCount": topic_count,
        "connectionCount": connection_count,
        "vaultPath": str(hippo_dir.parent),
    }

    html_content = _generate_html(output)

    graph_html_path = get_graph_path().parent / "graph.html"
    graph_html_path.parent.mkdir(parents=True, exist_ok=True)
    graph_html_path.write_text(html_content)

    return graph_html_path


def _generate_html(data: dict) -> str:
    json_data = json.dumps(data, ensure_ascii=False)

    script_dir = Path(__file__).parent
    template_path = script_dir / "template.html"
    css_path = script_dir / "style.css"
    js_path = script_dir / "script.js"

    html_template = template_path.read_text()
    css = css_path.read_text()
    js = js_path.read_text()

    html = html_template.replace("{{CSS}}", css)
    html = html.replace("{{JS}}", js)
    html = html.replace("{{DATA}}", json_data)

    return html
